# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: 
    - t3.medium
    - t3a.medium
    - m5.large
  spot: true
  desiredCapacity: 2